# Generated by Django 5.2.6 on 2025-11-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_remove_account_project_remove_billingcycle_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingcycle',
            name='account',
        ),
        migrations.RemoveField(
            model_name='billingcycle',
            name='customer',
        ),
    ]
