# Generated by Django 5.2.6 on 2025-11-05 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_remove_billingcycle_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcycle',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_billing_cycles', to='customers.account'),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_billing_cycles', to='customers.customer'),
        ),
    ]
