version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: excis-billing-db
    command: ["--default-authentication-plugin=mysql_native_password", "--sql-mode=STRICT_TRANS_TABLES"]
    environment:
      MYSQL_DATABASE: pickfres_billing
      MYSQL_USER: pickfres_billingAccess
      MYSQL_PASSWORD: Templates2025
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: excis-billing-web
    environment:
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0"
      DJANGO_SECRET_KEY: "dev-secret-key-change-me"
      MYSQL_DATABASE: pickfres_billing
      MYSQL_USER: pickfres_billingAccess
      MYSQL_PASSWORD: Templates2025
      MYSQL_HOST: db
      MYSQL_PORT: "3306"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - logs_volume:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
  static_volume:
  media_volume:
  logs_volume:
