version: "3.9"
services:
  web:
    build: .
    container_name: excis-billing-web
    environment:
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0"
      DJANGO_SECRET_KEY: "dev-secret-key-change-me"
      MYSQL_DATABASE: pickfres_billing
      MYSQL_USER: pickfres_billingAccess
      MYSQL_PASSWORD: Templates2025
      MYSQL_HOST: host.docker.internal   # Connects to your local MySQL
      MYSQL_PORT: "3306"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - logs_volume:/app/logs
    ports:
      - "8000:8000"

volumes:
  static_volume:
  media_volume:
  logs_volume:
