# Generated by Django 5.2.6 on 2025-11-06 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0012_rename_file_purchaseorderattachment_pdf_file_and_more'),
        ('rate_cards', '0005_alter_servicerate_rate_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratecard',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ratecards', to='purchase_orders.purchaseorder'),
        ),
    ]
