# Generated by Django 6.0 on 2026-01-10 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingrunattachment_billingrunlineitem_and_more'),
        ('customers', '0013_account_contact_file_account_ticket_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, max_length=100)),
                ('band_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['ticket_number', 'customer'], name='billing_ban_ticket__6eece5_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinalTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, max_length=100)),
                ('request_id', models.CharField(db_index=True, max_length=100)),
                ('data_table', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['request_id'], name='billing_fin_request_8361e4_idx'), models.Index(fields=['ticket_number'], name='billing_fin_ticket__187b4b_idx')],
            },
        ),
    ]
