# Generated by Django 6.0 on 2026-01-13 20:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bandtable_finalticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandtable',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='finalticket',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
