# Generated by Django 6.0.1 on 2026-02-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_finalticket_band_initialticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalticket',
            name='file_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initialticket',
            name='file_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
