# Generated by Django 6.0 on 2026-01-13 20:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_bandtable_uuid_finalticket_uuid'),
        ('customers', '0013_account_contact_file_account_ticket_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalticket',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='billing.bandtable'),
        ),
        migrations.CreateModel(
            name='InitialTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ticket_number', models.CharField(db_index=True, max_length=100)),
                ('request_id', models.CharField(db_index=True, max_length=100)),
                ('data_table', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.AddField(
            model_name='finalticket',
            name='initial_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_tickets', to='billing.initialticket'),
        ),
        migrations.AddIndex(
            model_name='initialticket',
            index=models.Index(fields=['request_id'], name='billing_ini_request_12074a_idx'),
        ),
        migrations.AddIndex(
            model_name='initialticket',
            index=models.Index(fields=['ticket_number'], name='billing_ini_ticket__33bd45_idx'),
        ),
    ]
