# Generated by Django 5.2.6 on 2025-12-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_billingcycle_account_billingcycle_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contact_file',
            field=models.FileField(blank=True, help_text='Upload Contact File', null=True, upload_to='accounts/contacts/'),
        ),
        migrations.AddField(
            model_name='account',
            name='ticket_report',
            field=models.FileField(blank=True, help_text='Upload Ticket Report', null=True, upload_to='accounts/reports/'),
        ),
    ]
