# Generated by Django 5.2.6 on 2025-10-21 11:47
# SAFE VERSION - Preserves existing functionality

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def generate_unique_uuids(apps, schema_editor):
    """Generate unique UUIDs for existing PO records"""
    PurchaseOrder = apps.get_model('purchase_orders', 'PurchaseOrder')
    
    for po in PurchaseOrder.objects.all():
        if not po.uuid:
            po.uuid = uuid.uuid4()
            po.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_swap_currency_fields'),
        ('purchase_orders', '0009_remove_purchaseorder_purchase_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ========================================
        # STEP 1: Add UUID field (nullable first)
        # ========================================
        migrations.AddField(
            model_name='purchaseorder',
            name='uuid',
            field=models.UUIDField(
                null=True,
                blank=True,
                editable=False,
                help_text='Unique identifier for API and external references'
            ),
        ),
        
        # ========================================
        # STEP 2: Populate UUIDs for existing records
        # ========================================
        migrations.RunPython(
            generate_unique_uuids,
            reverse_code=migrations.RunPython.noop
        ),
        
        # ========================================
        # STEP 3: Make UUID non-nullable and unique
        # ========================================
        migrations.AlterField(
            model_name='purchaseorder',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                db_index=True,
                help_text='Unique identifier for API and external references'
            ),
        ),
        
        # ========================================
        # STEP 4: Add new fields (all nullable to be safe)
        # ========================================
        migrations.AddField(
            model_name='purchaseorder',
            name='project',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sdm',
            field=models.CharField(
                blank=True, 
                max_length=200, 
                null=True, 
                verbose_name='Service Delivery Manager'
            ),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='bill_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='work_done',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='expiration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='client_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        
        # ========================================
        # STEP 5: Update existing fields (safe changes only)
        # ========================================
        migrations.AlterField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(
                default='USD',
                help_text='3-letter currency code (e.g., USD, EUR, GBP)',
                max_length=3
            ),
        ),
        
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier_name',
            field=models.CharField(
                blank=True, 
                help_text='Supplier name from CSV/PDF', 
                max_length=255, 
                null=True
            ),
        ),
        
        migrations.AlterField(
            model_name='purchaseorder',
            name='from_company',
            field=models.CharField(
                blank=True, 
                help_text='Ordering company from CSV/PDF', 
                max_length=255, 
                null=True
            ),
        ),
        
        # ========================================
        # STEP 6: Update model metadata
        # ========================================
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={
                'ordering': ['-created_at'], 
                'verbose_name': 'Purchase Order', 
                'verbose_name_plural': 'Purchase Orders'
            },
        ),
        
        migrations.AlterModelOptions(
            name='pobalancenotification',
            options={
                'ordering': ['-created_at'], 
                'verbose_name': 'PO Balance Notification', 
                'verbose_name_plural': 'PO Balance Notifications'
            },
        ),
        
        migrations.AlterModelOptions(
            name='purchaseorderattachment',
            options={
                'ordering': ['-uploaded_at'], 
                'verbose_name': 'Purchase Order Attachment', 
                'verbose_name_plural': 'Purchase Order Attachments'
            },
        ),
        
        migrations.AlterModelOptions(
            name='purchaseorderchangelog',
            options={
                'ordering': ['-changed_at'], 
                'verbose_name': 'Purchase Order Change Log', 
                'verbose_name_plural': 'Purchase Order Change Logs'
            },
        ),
        
        # ========================================
        # STEP 7: Add database indexes
        # ========================================
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['uuid'], name='purchase_or_uuid_idx'),
        ),
    ]