# Generated by Django 5.2.6 on 2025-10-21 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0010_purchaseordercsv_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='purchase_orders/csvs/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('extraction_success', models.BooleanField(default=False)),
                ('extraction_errors', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Purchase Order CSV',
                'verbose_name_plural': 'Purchase Order CSVs',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='purchaseorderpdf',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchaseorderpdf',
            name='uploaded_by',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='purchase_or_uuid_7ca960_idx',
            old_name='purchase_or_uuid_idx',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='remaining_balance',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('low_balance', 'Low Balance'), ('expiring_soon', 'Expiring Soon'), ('fully_utilized', 'Fully Utilized')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseordercsv',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csv_uploads', to='purchase_orders.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseordercsv',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PurchaseOrderPDF',
        ),
    ]
