# Generated by Django 5.2.6 on 2025-11-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0010_purchaseordercsv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='excis_entity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
