# Generated by Django 5.2.6 on 2025-11-04 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0011_purchaseorder_excis_entity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderattachment',
            old_name='file',
            new_name='pdf_file',
        ),
        migrations.AlterField(
            model_name='purchaseorderattachment',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='purchase_orders.purchaseorder'),
        ),
    ]
