# Generated by Django 5.2.6 on 2025-11-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0012_rename_file_purchaseorderattachment_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
