# Generated by Django 5.2.6 on 2025-11-06 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0013_alter_purchaseorder_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='valid_until',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
