# Generated by Django 5.2.6 on 2025-11-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0014_alter_purchaseorder_valid_until'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='purchase_or_uuid_7ca960_idx',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='uuid',
        ),
    ]
