# Generated by Django 6.0.2 on 2026-02-22 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0016_add_review_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='requires_review',
            field=models.BooleanField(blank=True, default=False, help_text='Flag indicating this PO needs manual review'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Notes from the review process'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='review_status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('pending_review', 'Pending Review'), ('rejected', 'Rejected'), ('active', 'Active')], default='active', help_text='Review status for manual verification', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When this PO was reviewed', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='User who reviewed this PO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
